name = "chat-room"
main = "workers/chat-room.ts"
compatibility_date = "2024-12-01"
account_id = "71184b988be37c368ead7c17a3055918"

[durable_objects]
bindings = [{ name = "CHAT_ROOM", class_name = "ChatRoom" }]

[[migrations]]
tag = "v1"
new_classes = ["ChatRoom"]
